# Generated by Django 5.1.6 on 2026-08-06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("signup", "Signup"),
                    ("reset", "Reset"),
                    ("verify", "Verify"),
                    ("phone_login", "Phone Login"),
                    ("verify_phone", "Verify Phone"),
                    ("verify_email", "Verify Email"),
                    ("admin_panel", "Admin Panel"),
                ],
                default="login",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AdminPanelSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("last_activity_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_panel_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "-last_activity_at"], name="accounts_ad_user_id_6f0a0a_idx")
                ],
            },
        ),
    ]
