# Generated by Django 4.2.7 on 2026-08-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_homeoffersection_max_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('home', 'Home'), ('offers', 'Offers'), ('festive', 'Festive'), ('coupons', 'Coupons'), ('brands', 'Brands'), ('combos', 'Combos')], default='home', max_length=20),
        ),
    ]
