# Generated by Django 4.2.7 on 2026-08-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_home_section_widget_layouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeoffersection',
            name='layout',
            field=models.CharField(choices=[('rail', 'Product rail'), ('countdown_rail', 'Flash sale (countdown)'), ('budget_rail', 'Budget store rail'), ('deal_card', 'Deal of the day card'), ('categories', 'Shop by category'), ('offers_strip', "Today's offers strip"), ('coupon_strip', 'Coupons strip'), ('festive_banners', 'Festival banner carousel'), ('shop_by_need', 'Shop by need grid'), ('brands', 'Featured brands'), ('recently_viewed', 'Recently viewed'), ('service_promises', 'Service promises')], default='rail', max_length=30),
        ),
    ]
