from django.conf import settings
from django.conf.urls.static import static
from django.http import JsonResponse
from django.urls import include, path

from config.health import health_view

from accounts.admin_security_views import (
    AdminPanelOtpRequestView,
    AdminPanelOtpVerifyView,
    AdminPanelSessionView,
)
from accounts.admin_views import (
    AdminBannerView,
    AdminBrandView,
    AdminCategoryView,
    AdminCouponView,
    AdminCustomerDetailView,
    AdminCustomerListView,
    AdminDashboardView,
    AdminOrderDetailView,
    AdminOrderListView,
    AdminProductView,
    AdminProductPlacementView,
    AdminReturnView,
    AdminReviewView,
    AdminSalesReportView,
    AdminSettingsView,
    AdminStoreView,
    AdminUserVerificationView,
    AdminBroadcastNotificationView,
    MediaUploadView,
)
from accounts.views import (
    AddressDefaultView,
    AddressDetailView,
    AddressListView,
    BootstrapDemoUsersView,
    LoginView,
    MeView,
    OtpRequestView,
    OtpVerifyView,
    ProfileAvatarUploadView,
    ProfileOtpRequestView,
    ProfileOtpVerifyView,
    RefreshView,
    VerificationView,
)
from blog.views import AdminBlogView, BlogDetailView, BlogListView
from catalog.views import (
    BannerListView,
    BrandDirectoryView,
    CategoryListView,
    CategoryProductsView,
    CombosView,
    CouponListView,
    DealsView,
    HomeView,
    OffersView,
    ProductDetailView,
    ProductListView,
    ProductReviewsView,
)
from locations.views import ReverseGeocodeView, StoreListView
from notifications.views import (
    NotificationDeleteView,
    NotificationListView,
    NotificationReadAllView,
    NotificationReadView,
)
from orders.views import (
    CartDetailView,
    CartView,
    OrderCancelView,
    OrderDetailView,
    OrderListView,
    OrderReturnView,
    WishlistDetailView,
    WishlistView,
)
from storeops.admin_views import (
    AdminActivityLogView,
    AdminBOGOView,
    AdminCategoryDiscountView,
    AdminDeliveryAssignView,
    AdminDeliveryPerformanceView,
    AdminFeedbackView,
    AdminPaymentReportView,
    AdminPincodeView,
    AdminRefundView,
    AdminRiderView,
    AdminTicketView,
    AdminUserManageView,
)
from storeops.views import (
    AccountDeleteView,
    ActivePromotionsView,
    AppConfigView,
    FeedbackView,
    LoyaltyView,
    OrderInvoiceView,
    PaymentIntentView,
    PaymentVerifyView,
    PincodeCheckView,
    PriceWatchView,
    ProductReviewSubmitView,
    PushSubscribeView,
    ReferralView,
    SupportTicketView,
    WalletView,
)

urlpatterns = [
    path(
        "",
        lambda _request: JsonResponse(
            {
                "service": "Sri Mahalakshmi Stores API",
                "status": "ok",
                "health": "/api/v1/health/",
                "docs": "Use the frontend at http://localhost:8080/",
            }
        ),
    ),
    path("api/v1/health/", health_view),
    path("api/v1/auth/otp/request/", OtpRequestView.as_view()),
    path("api/v1/auth/otp/verify/", OtpVerifyView.as_view()),
    path("api/v1/auth/login/", LoginView.as_view()),
    path("api/v1/auth/refresh/", RefreshView.as_view()),
    path("api/v1/bootstrap/demo-users/", BootstrapDemoUsersView.as_view()),
    path("api/v1/me/", MeView.as_view()),
    path("api/v1/me/avatar/", ProfileAvatarUploadView.as_view()),
    path("api/v1/me/otp/request/", ProfileOtpRequestView.as_view()),
    path("api/v1/me/otp/verify/", ProfileOtpVerifyView.as_view()),
    path("api/v1/me/addresses/", AddressListView.as_view()),
    path("api/v1/me/addresses/<uuid:pk>/", AddressDetailView.as_view()),
    path("api/v1/me/addresses/<uuid:pk>/default/", AddressDefaultView.as_view()),
    path("api/v1/account/verification/", VerificationView.as_view()),
    path("api/v1/home/", HomeView.as_view()),
    path("api/v1/categories/", CategoryListView.as_view()),
    path("api/v1/categories/<slug:slug>/products/", CategoryProductsView.as_view()),
    path("api/v1/products/", ProductListView.as_view()),
    path("api/v1/products/<slug:slug>/", ProductDetailView.as_view()),
    path("api/v1/products/<uuid:product_id>/reviews/", ProductReviewsView.as_view()),
    path("api/v1/products/<uuid:product_id>/reviews/submit/", ProductReviewSubmitView.as_view()),
    path("api/v1/banners/", BannerListView.as_view()),
    path("api/v1/catalog/deals/", DealsView.as_view()),
    path("api/v1/catalog/combos/", CombosView.as_view()),
    path("api/v1/catalog/offers/", OffersView.as_view()),
    path("api/v1/catalog/brands/directory/", BrandDirectoryView.as_view()),
    path("api/v1/coupons/", CouponListView.as_view()),
    path("api/v1/cart/", CartView.as_view()),
    path("api/v1/cart/<uuid:pk>/", CartDetailView.as_view()),
    path("api/v1/wishlist/", WishlistView.as_view()),
    path("api/v1/wishlist/<uuid:product_id>/", WishlistDetailView.as_view()),
    path("api/v1/orders/", OrderListView.as_view()),
    path("api/v1/orders/<uuid:pk>/", OrderDetailView.as_view()),
    path("api/v1/orders/<uuid:pk>/cancel/", OrderCancelView.as_view()),
    path("api/v1/returns/", OrderReturnView.as_view()),
    path("api/v1/support/tickets/", SupportTicketView.as_view()),
    path("api/v1/support/feedback/", FeedbackView.as_view()),
    path("api/v1/pincodes/check/", PincodeCheckView.as_view()),
    path("api/v1/wallet/", WalletView.as_view()),
    path("api/v1/loyalty/", LoyaltyView.as_view()),
    path("api/v1/referral/", ReferralView.as_view()),
    path("api/v1/price-watches/", PriceWatchView.as_view()),
    path("api/v1/push/subscribe/", PushSubscribeView.as_view()),
    path("api/v1/app/config/", AppConfigView.as_view()),
    path("api/v1/me/delete/", AccountDeleteView.as_view()),
    path("api/v1/payments/intent/", PaymentIntentView.as_view()),
    path("api/v1/payments/verify/", PaymentVerifyView.as_view()),
    path("api/v1/orders/<uuid:pk>/invoice/", OrderInvoiceView.as_view()),
    path("api/v1/promotions/", ActivePromotionsView.as_view()),
    path("api/v1/stores/", StoreListView.as_view()),
    path("api/v1/geocode/reverse/", ReverseGeocodeView.as_view()),
    path("api/v1/notifications/", NotificationListView.as_view()),
    path("api/v1/notifications/read-all/", NotificationReadAllView.as_view()),
    path("api/v1/notifications/<uuid:pk>/read/", NotificationReadView.as_view()),
    path("api/v1/notifications/<uuid:pk>/", NotificationDeleteView.as_view()),
    path("api/v1/blog/", BlogListView.as_view()),
    path("api/v1/blog/<slug:slug>/", BlogDetailView.as_view()),
    path("api/v1/media/", MediaUploadView.as_view()),
    # Admin panel step-up security (OTP + idle session)
    path("api/v1/admin-api/access/otp/request/", AdminPanelOtpRequestView.as_view()),
    path("api/v1/admin-api/access/otp/verify/", AdminPanelOtpVerifyView.as_view()),
    path("api/v1/admin-api/access/session/", AdminPanelSessionView.as_view()),
    # Admin API
    path("api/v1/admin-api/dashboard/", AdminDashboardView.as_view()),
    path("api/v1/admin-api/orders/", AdminOrderListView.as_view()),
    path("api/v1/admin-api/orders/<uuid:pk>/", AdminOrderDetailView.as_view()),
    path("api/v1/admin-api/products/", AdminProductView.as_view()),
    path("api/v1/admin-api/products/placements/", AdminProductPlacementView.as_view()),
    path("api/v1/admin-api/categories/", AdminCategoryView.as_view()),
    path("api/v1/admin-api/banners/", AdminBannerView.as_view()),
    path("api/v1/admin-api/brands/", AdminBrandView.as_view()),
    path("api/v1/admin-api/coupons/", AdminCouponView.as_view()),
    path("api/v1/admin-api/stores/", AdminStoreView.as_view()),
    path("api/v1/admin-api/customers/", AdminCustomerListView.as_view()),
    path("api/v1/admin-api/customers/<uuid:pk>/", AdminCustomerDetailView.as_view()),
    path("api/v1/admin-api/users/", AdminUserVerificationView.as_view()),
    path("api/v1/admin-api/users/<uuid:pk>/verification/", AdminUserVerificationView.as_view()),
    path("api/v1/admin-api/settings/", AdminSettingsView.as_view()),
    path("api/v1/admin-api/reviews/", AdminReviewView.as_view()),
    path("api/v1/admin-api/returns/", AdminReturnView.as_view()),
    path("api/v1/admin-api/reports/sales/", AdminSalesReportView.as_view()),
    path("api/v1/admin-api/notifications/broadcast/", AdminBroadcastNotificationView.as_view()),
    path("api/v1/admin-api/tickets/", AdminTicketView.as_view()),
    path("api/v1/admin-api/feedback/", AdminFeedbackView.as_view()),
    path("api/v1/admin-api/activity-logs/", AdminActivityLogView.as_view()),
    path("api/v1/admin-api/users/<uuid:pk>/manage/", AdminUserManageView.as_view()),
    path("api/v1/admin-api/pincodes/", AdminPincodeView.as_view()),
    path("api/v1/admin-api/riders/", AdminRiderView.as_view()),
    path("api/v1/admin-api/delivery/", AdminDeliveryAssignView.as_view()),
    path("api/v1/admin-api/delivery/performance/", AdminDeliveryPerformanceView.as_view()),
    path("api/v1/admin-api/payments/", AdminPaymentReportView.as_view()),
    path("api/v1/admin-api/refunds/", AdminRefundView.as_view()),
    path("api/v1/admin-api/promotions/bogo/", AdminBOGOView.as_view()),
    path("api/v1/admin-api/promotions/category-discounts/", AdminCategoryDiscountView.as_view()),
    path("api/v1/admin/blog/", AdminBlogView.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
