# Generated by Django 4.2.7 on 2026-08-02 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('body', models.TextField()),
                ('cover_url', models.URLField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('read_minutes', models.IntegerField(default=5)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
