#!/usr/bin/env node
/**
 * Detects LAN IP and writes mobile dev config so phones can reach
 * your local Vite app + Django API (not Lovable).
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

function getLanIp() {
  if (process.env.MOBILE_HOST?.trim()) return process.env.MOBILE_HOST.trim();
  const nets = os.networkInterfaces();

  // 1. Prefer real Wi‑Fi / WLAN adapter by interface name.
  for (const [name, ifaces] of Object.entries(nets)) {
    if (!/wi-?fi|wlan|wireless/i.test(name)) continue;
    for (const net of ifaces ?? []) {
      if (net.family === "IPv4" && !net.internal) return net.address;
    }
  }

  // 2. Windows mobile hotspot (phone → PC hotspot, IP usually 192.168.137.1).
  for (const [name, ifaces] of Object.entries(nets)) {
    if (!/wi-?fi direct|hotspot|local area connection/i.test(name)) continue;
    for (const net of ifaces ?? []) {
      if (net.family === "IPv4" && !net.internal) return net.address;
    }
  }

  const candidates = [];
  for (const ifaces of Object.values(nets)) {
    for (const net of ifaces ?? []) {
      if (net.family === "IPv4" && !net.internal) candidates.push(net.address);
    }
  }
  // 3. Prefer home Wi‑Fi / hotspot ranges over VMware/Hyper-V virtual adapters.
  const wifiLike = candidates.find((ip) =>
    /^192\.168\.(0|1|2|3|4|5|137)\.\d+$/.test(ip),
  );
  return wifiLike ?? candidates[0] ?? "127.0.0.1";
}

const ip = getLanIp();
const webPort = process.env.MOBILE_WEB_PORT?.trim() || "8080";
const apiPort = process.env.MOBILE_API_PORT?.trim() || "8000";
// HTTP by default — Android WebView + self-signed HTTPS on LAN causes ERR_SSL_PROTOCOL_ERROR.
// Set MOBILE_HTTPS=1 only for iPhone Safari GPS testing.
const useHttps = process.env.MOBILE_HTTPS === "1";
const scheme = useHttps ? "https" : "http";
const serverUrl = `${scheme}://${ip}:${webPort}`;
// Relative path — Vite proxies /api/v1 → Django in dev.
// Absolute LAN URL — phone calls Django directly (works without Vite proxy).
const clientApiUrl = `/api/v1`;
const publicApi = (process.env.MOBILE_PUBLIC_API_URL || process.env.VITE_PUBLIC_API_URL || "").trim().replace(/\/$/, "");
const directApiUrl = publicApi || `http://${ip}:${apiPort}/api/v1`;
const serverApiUrl = `http://127.0.0.1:${apiPort}/api/v1`;

const mobileDir = path.join(root, "mobile");
fs.mkdirSync(mobileDir, { recursive: true });

const bundled = process.env.MOBILE_BUNDLED === "1" || process.argv.includes("--bundled");

const serverConfig = {
  mode: bundled ? "local-bundled" : "local",
  bundled,
  serverUrl: bundled ? "" : serverUrl,
  apiUrl: directApiUrl,
  clientApiUrl,
  serverApiUrl,
  host: ip,
  webPort,
  apiPort,
  updatedAt: new Date().toISOString(),
};

fs.writeFileSync(path.join(mobileDir, "capacitor.server.json"), JSON.stringify(serverConfig, null, 2));

const envLines = [
  `# Auto-generated by scripts/mobile-config.mjs — LAN mobile testing`,
  `VITE_API_URL=${directApiUrl}`,
  `API_URL=${serverApiUrl}`,
  `VITE_API_PROXY_TARGET=http://127.0.0.1:${apiPort}`,
  `VITE_APP_URL=${serverUrl}`,
  bundled ? `# CAPACITOR_SERVER_URL not set — UI bundled in APK` : `CAPACITOR_SERVER_URL=${serverUrl}`,
  ``,
];
fs.writeFileSync(path.join(root, ".env.mobile.local"), envLines.join("\n"));

const backendEnvPath = path.join(root, "backend", ".env");
if (fs.existsSync(backendEnvPath)) {
  let backendEnv = fs.readFileSync(backendEnvPath, "utf8");
  const corsOrigins = new Set(
    (backendEnv.match(/^CORS_ALLOWED_ORIGINS=(.*)$/m)?.[1] ?? "")
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean),
  );
  corsOrigins.add(serverUrl);
  corsOrigins.add(`http://${ip}:8080`);
  corsOrigins.add(`https://${ip}:8080`);
  corsOrigins.add("https://localhost");
  corsOrigins.add("http://localhost");
  corsOrigins.add("capacitor://localhost");
  corsOrigins.add("ionic://localhost");

  const hosts = new Set(
    (backendEnv.match(/^ALLOWED_HOSTS=(.*)$/m)?.[1] ?? "localhost,127.0.0.1")
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean),
  );
  hosts.add(ip);
  hosts.add("0.0.0.0");

  if (/^ALLOWED_HOSTS=/m.test(backendEnv)) {
    backendEnv = backendEnv.replace(/^ALLOWED_HOSTS=.*$/m, `ALLOWED_HOSTS=${[...hosts].join(",")}`);
  } else {
    backendEnv += `\nALLOWED_HOSTS=${[...hosts].join(",")}\n`;
  }

  if (/^CORS_ALLOWED_ORIGINS=/m.test(backendEnv)) {
    backendEnv = backendEnv.replace(
      /^CORS_ALLOWED_ORIGINS=.*$/m,
      `CORS_ALLOWED_ORIGINS=${[...corsOrigins].join(",")}`,
    );
  } else {
    backendEnv += `\nCORS_ALLOWED_ORIGINS=${[...corsOrigins].join(",")}\n`;
  }

  fs.writeFileSync(backendEnvPath, backendEnv);
}

console.log("");
console.log("Mobile dev config ready");
console.log("=========================");
console.log(`PC LAN IP:     ${ip}`);
console.log(`Web app URL:   ${serverUrl}`);
console.log(`Client API:    ${directApiUrl}`);
console.log(`Server API:    ${serverApiUrl}`);
console.log("");
console.log("Next steps:");
console.log("  1. npm run backend:mobile     (Django on 0.0.0.0:8000)");
console.log("  2. npm run dev:mobile         (HTTP Vite on LAN, port 8080)");
console.log("  3. npm run mobile:apk         (rebuild Android APK)");
console.log("  4. npm run cap:sync           (sync native projects with capacitor.config.ts)");
if (useHttps) {
  console.log("");
  console.log("HTTPS mode: iPhone may need Advanced → Proceed for the self-signed certificate.");
} else {
  console.log("");
  console.log("Android: reinstall APK after npm run mobile:apk:local if your Wi‑Fi IP changed.");
  console.log("");
  console.log("If phone cannot reach this PC (ERR_ADDRESS_UNREACHABLE):");
  console.log("  • Turn on Windows Mobile Hotspot, connect phone to it, then: npm run mobile:hotspot");
  console.log("  • Run npm run mobile:firewall (as Administrator if needed)");
  console.log("  • On phone Chrome open: " + serverUrl + " — must load before the app will work");
}
