/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as DevLoginTestRouteImport } from './routes/dev/login-test'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminStoresRouteImport } from './routes/admin/stores'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminReturnsRouteImport } from './routes/admin/returns'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminBrandsRouteImport } from './routes/admin/brands'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedVerifyAccountRouteImport } from './routes/_authenticated/verify-account'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLanguageRouteImport } from './routes/_authenticated/language'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedAddressesRouteImport } from './routes/_authenticated/addresses'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AdminCustomerIdRouteImport } from './routes/admin/customer.$id'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders/$id'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginTestRoute = DevLoginTestRouteImport.update({
  id: '/dev/login-test',
  path: '/dev/login-test',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerifyAccountRoute =
  AuthenticatedVerifyAccountRouteImport.update({
    id: '/verify-account',
    path: '/verify-account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLanguageRoute = AuthenticatedLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddressesRoute = AuthenticatedAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminCustomerIdRoute = AdminCustomerIdRouteImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/stores': typeof StoresRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/addresses': typeof AuthenticatedAddressesRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/language': typeof AuthenticatedLanguageRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/verify-account': typeof AuthenticatedVerifyAccountRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dev/login-test': typeof DevLoginTestRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/admin/customer/$id': typeof AdminCustomerIdRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/stores': typeof StoresRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/addresses': typeof AuthenticatedAddressesRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/language': typeof AuthenticatedLanguageRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/verify-account': typeof AuthenticatedVerifyAccountRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dev/login-test': typeof DevLoginTestRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/admin/customer/$id': typeof AdminCustomerIdRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/stores': typeof StoresRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/_authenticated/addresses': typeof AuthenticatedAddressesRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/language': typeof AuthenticatedLanguageRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/verify-account': typeof AuthenticatedVerifyAccountRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/users': typeof AdminUsersRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dev/login-test': typeof DevLoginTestRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/admin/customer/$id': typeof AdminCustomerIdRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/auth'
    | '/brands'
    | '/categories'
    | '/contact'
    | '/coupons'
    | '/deals'
    | '/faq'
    | '/feedback'
    | '/help'
    | '/maintenance'
    | '/offers'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/stores'
    | '/terms'
    | '/testimonials'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/language'
    | '/notifications'
    | '/profile'
    | '/referral'
    | '/rewards'
    | '/verify-account'
    | '/wallet'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/blogs/$slug'
    | '/category/$slug'
    | '/dev/login-test'
    | '/product/$slug'
    | '/admin/'
    | '/blogs/'
    | '/orders/$id'
    | '/admin/customer/$id'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/brands'
    | '/categories'
    | '/contact'
    | '/coupons'
    | '/deals'
    | '/faq'
    | '/feedback'
    | '/help'
    | '/maintenance'
    | '/offers'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/stores'
    | '/terms'
    | '/testimonials'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/language'
    | '/notifications'
    | '/profile'
    | '/referral'
    | '/rewards'
    | '/verify-account'
    | '/wallet'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/blogs/$slug'
    | '/category/$slug'
    | '/dev/login-test'
    | '/product/$slug'
    | '/admin'
    | '/blogs'
    | '/orders/$id'
    | '/admin/customer/$id'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/about'
    | '/auth'
    | '/brands'
    | '/categories'
    | '/contact'
    | '/coupons'
    | '/deals'
    | '/faq'
    | '/feedback'
    | '/help'
    | '/maintenance'
    | '/offers'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/stores'
    | '/terms'
    | '/testimonials'
    | '/_authenticated/addresses'
    | '/_authenticated/cart'
    | '/_authenticated/checkout'
    | '/_authenticated/language'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/referral'
    | '/_authenticated/rewards'
    | '/_authenticated/verify-account'
    | '/_authenticated/wallet'
    | '/_authenticated/wishlist'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stores'
    | '/admin/users'
    | '/blogs/$slug'
    | '/category/$slug'
    | '/dev/login-test'
    | '/product/$slug'
    | '/admin/'
    | '/blogs/'
    | '/_authenticated/orders/$id'
    | '/admin/customer/$id'
    | '/_authenticated/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BrandsRoute: typeof BrandsRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  CouponsRoute: typeof CouponsRoute
  DealsRoute: typeof DealsRoute
  FaqRoute: typeof FaqRoute
  FeedbackRoute: typeof FeedbackRoute
  HelpRoute: typeof HelpRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OffersRoute: typeof OffersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  StoresRoute: typeof StoresRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DevLoginTestRoute: typeof DevLoginTestRoute
  ProductSlugRoute: typeof ProductSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/login-test': {
      id: '/dev/login-test'
      path: '/dev/login-test'
      fullPath: '/dev/login-test'
      preLoaderRoute: typeof DevLoginTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verify-account': {
      id: '/_authenticated/verify-account'
      path: '/verify-account'
      fullPath: '/verify-account'
      preLoaderRoute: typeof AuthenticatedVerifyAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/language': {
      id: '/_authenticated/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof AuthenticatedLanguageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/addresses': {
      id: '/_authenticated/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AuthenticatedAddressesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/customer/$id': {
      id: '/admin/customer/$id'
      path: '/customer/$id'
      fullPath: '/admin/customer/$id'
      preLoaderRoute: typeof AdminCustomerIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddressesRoute: typeof AuthenticatedAddressesRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedLanguageRoute: typeof AuthenticatedLanguageRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedVerifyAccountRoute: typeof AuthenticatedVerifyAccountRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddressesRoute: AuthenticatedAddressesRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedLanguageRoute: AuthenticatedLanguageRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedVerifyAccountRoute: AuthenticatedVerifyAccountRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomerIdRoute: typeof AdminCustomerIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBrandsRoute: AdminBrandsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomerIdRoute: AdminCustomerIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BrandsRoute: BrandsRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  CouponsRoute: CouponsRoute,
  DealsRoute: DealsRoute,
  FaqRoute: FaqRoute,
  FeedbackRoute: FeedbackRoute,
  HelpRoute: HelpRoute,
  MaintenanceRoute: MaintenanceRoute,
  OffersRoute: OffersRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  StoresRoute: StoresRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  DevLoginTestRoute: DevLoginTestRoute,
  ProductSlugRoute: ProductSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
